<?php

return [
    [
        'group_key' => 'app',
        'name' => '系统配置',
        'sort' => 10,
        'children' => [
        ],
    ],
    [
        'group_key' => 'wechat',
        'name' => '微信配置',
        'sort' => 9,
        'children' => [],
    ],
    [
        'group_key' => 'mail',
        'name' => '邮件配置',
        'sort' => 7,
        'children' => [
            [
                'label' => '邮件引擎',
                'key' => 'mail_host',
                'config_file_key' => 'mail.host',
                'val' => 'smtp.163.com',
                'type' => 2,
                'tips' => 'eg: smtp.163.com',
            ],
            [
                'label' => 'SMTP端口',
                'key' => 'mail_port',
                'config_file_key' => 'mail.port',
                'val' => '465',
                'type' => 2,
                'tips' => 'eg:25/465',
            ],
            [
                'label' => '用户名',
                'key' => 'mail_username',
                'config_file_key' => 'mail.username',
                'val' => '',
                'type' => 2,
                'tips' => '邮箱账号',
            ],
            [
                'label' => '邮箱授权密码',
                'key' => 'mail_password',
                'config_file_key' => 'mail.password',
                'val' => '',
                'type' => 2,
                'tips' => '邮箱授权密码',
            ],
            [
                'label' => '邮件发送人名称',
                'key' => 'mail_nickname',
                'config_file_key' => 'mail.from.name',
                'val' => '',
                'type' => 2,
                'tips' => '沙屿沫',
            ],
            [
                'label' => '邮件发送地址',
                'key' => 'mail_from_address',
                'config_file_key' => 'mail.from.address',
                'val' => '',
                'type' => 2,
                'tips' => 'eg: xxx@163.com',
            ],
            [
                'label' => '邮件接收地址',
                'key' => 'mail_receive_address',
                'config_file_key' => 'my.system.mail_receive_address',
                'val' => '',
                'type' => 2,
                'tips' => '邮件提醒接收地址',
            ],
        ],
    ],
    [
        'group_key' => 'upload',
        'name' => '上传配置',
        'sort' => 10,
        'children' => [
            [
                'label' => '默认上传方式',
                'key' => 'upload_mode',
                'config_file_key' => 'my.upload.storage',
                'val' => 'public',
                'type' => 4,
                'tips' => '',
                'options' => [
                    [
                        'value' => 'public',
                        'label' => '本地',
                    ],
                    [
                        'value' => 'qiniu',
                        'label' => '七牛云',
                    ],
                    [
                        'value' => 'oss',
                        'label' => '阿里云',
                    ],
                ],
            ],
            [
                'label' => '存储Bucket',
                'key' => 'upload_bucket',
                'config_file_key' => 'filesystems.disks.qiniu.bucket',
                'val' => '',
                'type' => 2,
                'tips' => '仅适用于七牛云存储',
            ],
            [
                'label' => 'ACCESS_KEY',
                'key' => 'upload_access_key',
                'config_file_key' => 'filesystems.disks.qiniu.access_key',
                'val' => '',
                'type' => 2,
                'tips' => '仅适用于七牛云存储',
            ],
            [
                'label' => 'SECRET_KEY',
                'key' => 'upload_secret_key',
                'config_file_key' => 'filesystems.disks.qiniu.secret_key',
                'val' => '',
                'type' => 2,
                'tips' => '仅适用于七牛云存储',
            ],
            [
                'label' => 'bucket域名',
                'key' => 'upload_domain',
                'config_file_key' => 'filesystems.disks.qiniu.domain',
                'val' => '',
                'type' => 2,
                'tips' => '仅适用于七牛云存储',
            ],
            [
                'label' => '存储Bucket',
                'key' => 'upload_bucket',
                'config_file_key' => 'filesystems.disks.oss.bucket',
                'val' => '',
                'type' => 2,
                'tips' => '仅适用于阿里云存储',
            ],
            [
                'label' => 'ACCESS_KEY',
                'key' => 'upload_access_key',
                'config_file_key' => 'filesystems.disks.oss.access_key',
                'val' => '',
                'type' => 2,
                'tips' => '仅适用于阿里云存储',
            ],
            [
                'label' => 'SECRET_KEY',
                'key' => 'upload_secret_key',
                'config_file_key' => 'filesystems.disks.oss.secret_key',
                'val' => '',
                'type' => 2,
                'tips' => '仅适用于阿里云存储',
            ],
            [
                'label' => 'bucket域名',
                'key' => 'upload_domain',
                'config_file_key' => 'filesystems.disks.oss.endpoint',
                'val' => '',
                'type' => 2,
                'tips' => '仅适用于阿里云存储',
            ],
        ],
    ],
];
