<?php

return [
    [
        'group_key' => 'app',
        'name' => '系统配置',
        'sort' => 10,
        'children' => [
            [
                'label' => '站点标题',
                'key' => 'site_title',
                'config_file_key' => 'frontend.site_title',
                'val' => '沙屿沫后台管理系统',
                'type' => 2,
                'tips' => '',
            ],
            [
                'label' => '关键词',
                'key' => 'site_keywords',
                'config_file_key' => 'frontend.site_keywords',
                'val' => '后台管理系统管理',
                'type' => 2,
                'tips' => '',
            ],
            [
                'label' => '描述',
                'key' => 'site_description',
                'config_file_key' => 'frontend.site_description',
                'val' => '沙屿沫后台管理系统, shayvmo-admin后台管理系统',
                'type' => 3,
                'tips' => '',
            ],
            [
                'label' => '网址',
                'key' => 'site_url',
                'config_file_key' => 'app.url',
                'val' => 'http://localhost',
                'type' => 2,
                'tips' => '网址',
            ],
        ],
    ],
    [
        'group_key' => 'wechat',
        'name' => '微信配置',
        'sort' => 9,
        'children' => [],
    ],
    [
        'group_key' => 'client',
        'name' => '客户端配置',
        'sort' => 8,
        'children' => [
            [
                'label' => 'ICP备案号',
                'key' => 'icp_no',
                'config_file_key' => 'frontend.icp_num',
                'val' => '粤ICP',
                'type' => 2,
                'tips' => '',
            ],
            [
                'label' => '备案名称',
                'key' => 'icp_title',
                'config_file_key' => 'frontend.icp_title',
                'val' => 'XX公司官网',
                'type' => 2,
                'tips' => '',
            ],
            [
                'label' => '工信部地址',
                'key' => 'icp_link',
                'config_file_key' => 'frontend.icp_link',
                'val' => 'http://beian.miit.gov.cn',
                'type' => 2,
                'tips' => '',
            ],
            [
                'label' => '邮箱',
                'key' => 'concat_email',
                'config_file_key' => 'frontend.concat_email',
                'val' => '',
                'type' => 2,
                'tips' => '',
            ],
            [
                'label' => '电话',
                'key' => 'concat_phone',
                'config_file_key' => 'frontend.concat_phone',
                'val' => '',
                'type' => 2,
                'tips' => '',
            ],
            [
                'label' => '公司地址',
                'key' => 'concat_address',
                'config_file_key' => 'frontend.concat_address',
                'val' => '',
                'type' => 2,
                'tips' => '',
            ],
        ],
    ],
    [
        'group_key' => 'mail',
        'name' => '邮件配置',
        'sort' => 7,
        'children' => [
            [
                'label' => '邮件引擎',
                'key' => 'mail_host',
                'config_file_key' => 'mail.host',
                'val' => 'smtp.163.com',
                'type' => 2,
                'tips' => 'eg: smtp.163.com',
            ],
            [
                'label' => 'SMTP端口',
                'key' => 'mail_port',
                'config_file_key' => 'mail.port',
                'val' => '465',
                'type' => 2,
                'tips' => 'eg:25/465',
            ],
            [
                'label' => '用户名',
                'key' => 'mail_username',
                'config_file_key' => 'mail.username',
                'val' => '',
                'type' => 2,
                'tips' => '邮箱账号',
            ],
            [
                'label' => '邮箱授权密码',
                'key' => 'mail_password',
                'config_file_key' => 'mail.password',
                'val' => '',
                'type' => 2,
                'tips' => '邮箱授权密码',
            ],
            [
                'label' => '邮件发送人名称',
                'key' => 'mail_nickname',
                'config_file_key' => 'mail.from.name',
                'val' => '',
                'type' => 2,
                'tips' => '沙屿沫',
            ],
            [
                'label' => '邮件发送地址',
                'key' => 'mail_from_address',
                'config_file_key' => 'mail.from.address',
                'val' => '',
                'type' => 2,
                'tips' => 'eg: xxx@163.com',
            ],
            [
                'label' => '邮件接收地址',
                'key' => 'mail_receive_address',
                'config_file_key' => 'my.system.mail_receive_address',
                'val' => '',
                'type' => 2,
                'tips' => '邮件提醒接收地址',
            ],
        ],
    ],
    [
        'group_key' => 'login_page',
        'name' => '登录页配置',
        'sort' => 6,
        'children' => [
            [
                'label' => '站点名称',
                'key' => 'site_name',
                'config_file_key' => 'frontend.site_name',
                'val' => '沙屿沫 Admin',
                'type' => 2,
                'tips' => '站点标题',
            ],
            [
                'label' => '站点名称(副)',
                'key' => 'site_aword',
                'config_file_key' => 'frontend.site_aword',
                'val' => '总 有 人 山 高 路 远 为 你 而 来',
                'type' => 2,
                'tips' => '',
            ],
            [
                'label' => '站点LOGO',
                'key' => 'site_logo',
                'config_file_key' => 'frontend.site_logo',
                'val' => '/static/admin/admin/images/logo.png',
                'type' => 2,
                'tips' => '最好不要修改, 如果需要修改, 建议是静态文件路径, 加入版本控制',
            ],
            [
                'label' => '登录页背景',
                'key' => 'login_background',
                'config_file_key' => 'frontend.login_background',
                'val' => '/static/admin/admin/images/background.svg',
                'type' => 2,
                'tips' => '最好不要修改, 如果需要修改, 建议是静态文件路径, 加入版本控制',
            ],
        ],
    ],
    [
        'group_key' => 'upload',
        'name' => '上传配置',
        'sort' => 10,
        'children' => [
            [
                'label' => '默认上传方式',
                'key' => 'upload_mode',
                'config_file_key' => 'my.upload.storage',
                'val' => 'public',
                'type' => 4,
                'tips' => '',
                'options' => [
                    [
                        'value' => 'public',
                        'label' => '本地',
                    ],
                    [
                        'value' => 'qiniu',
                        'label' => '七牛云',
                    ],
                    [
                        'value' => 'oss',
                        'label' => '阿里云',
                    ],
                ],
            ],
            [
                'label' => '存储Bucket',
                'key' => 'upload_bucket',
                'config_file_key' => 'filesystems.disks.qiniu.bucket',
                'val' => '',
                'type' => 2,
                'tips' => '仅适用于七牛云存储',
            ],
            [
                'label' => 'ACCESS_KEY',
                'key' => 'upload_access_key',
                'config_file_key' => 'filesystems.disks.qiniu.access_key',
                'val' => '',
                'type' => 2,
                'tips' => '仅适用于七牛云存储',
            ],
            [
                'label' => 'SECRET_KEY',
                'key' => 'upload_secret_key',
                'config_file_key' => 'filesystems.disks.qiniu.secret_key',
                'val' => '',
                'type' => 2,
                'tips' => '仅适用于七牛云存储',
            ],
            [
                'label' => 'bucket域名',
                'key' => 'upload_domain',
                'config_file_key' => 'filesystems.disks.qiniu.domain',
                'val' => '',
                'type' => 2,
                'tips' => '仅适用于七牛云存储',
            ],
            [
                'label' => '存储Bucket',
                'key' => 'upload_bucket',
                'config_file_key' => 'filesystems.disks.oss.bucket',
                'val' => '',
                'type' => 2,
                'tips' => '仅适用于阿里云存储',
            ],
            [
                'label' => 'ACCESS_KEY',
                'key' => 'upload_access_key',
                'config_file_key' => 'filesystems.disks.oss.access_key',
                'val' => '',
                'type' => 2,
                'tips' => '仅适用于阿里云存储',
            ],
            [
                'label' => 'SECRET_KEY',
                'key' => 'upload_secret_key',
                'config_file_key' => 'filesystems.disks.oss.secret_key',
                'val' => '',
                'type' => 2,
                'tips' => '仅适用于阿里云存储',
            ],
            [
                'label' => 'bucket域名',
                'key' => 'upload_domain',
                'config_file_key' => 'filesystems.disks.oss.endpoint',
                'val' => '',
                'type' => 2,
                'tips' => '仅适用于阿里云存储',
            ],
        ],
    ],
];
