<?php

return [
    [
        'name' => 'dashboard',
        'title' => '控制中心',
        'route' => '',
        'icon' => 'layui-icon-console',
        'type' => 1,
        'sort' => 100,
        'is_menu' => 1,
        'children' => [
            [
                'name' => 'dashboard.datacenter',
                'title' => '仪表盘',
                'route' => 'admin.datacenter',
                'icon' => 'layui-icon-console',
                'type' => 1,
                'sort' => 100,
                'is_menu' => 1,
            ],
            [
                'name' => 'demo',
                'title' => 'demo页',
                'route' => 'admin.demo',
                'icon' => 'layui-icon-template',
                'type' => 1,
                'sort' => 60,
                'is_menu' => 1,
            ],
        ],
    ],
    [
        'name' => 'system',
        'title' => '系统管理',
        'route' => '',
        'icon' => 'layui-icon-set',
        'type' => 1,
        'sort' => 80,
        'is_menu' => 1,
        'children' => [
            [
                'name' => 'system.permission',
                'title' => '权限管理',
                'route' => 'admin.permission',
                'icon' => 'layui-icon-circle',
                'type' => 1,
                'sort' => 17,
                'is_menu' => 1,
                'children' => [
                    [
                        'name' => 'system.permission.create',
                        'title' => '添加权限',
                        'route' => 'admin.permission.create',
                        'icon' => '',
                        'type' => 2,
                        'sort' => 18,
                        'is_menu' => 0,
                    ],
                    [
                        'name' => 'system.permission.edit',
                        'title' => '编辑权限',
                        'route' => 'admin.permission.edit',
                        'icon' => '',
                        'type' => 2,
                        'sort' => 19,
                        'is_menu' => 0,
                    ],
                    [
                        'name' => 'system.permission.destroy',
                        'title' => '删除权限',
                        'route' => 'admin.permission.destroy',
                        'icon' => '',
                        'type' => 2,
                        'sort' => 20,
                        'is_menu' => 0,
                    ],
                ],
            ],
            [
                'name' => 'system.role',
                'title' => '角色管理',
                'route' => 'admin.role',
                'icon' => 'layui-icon-template',
                'type' => 1,
                'sort' => 21,
                'is_menu' => 1,
                'children' => [
                    [
                        'name' => 'system.role.create',
                        'title' => '添加角色',
                        'route' => 'admin.role.create',
                        'icon' => '',
                        'type' => 2,
                        'sort' => 22,
                        'is_menu' => 0,
                    ],
                    [
                        'name' => 'system.role.edit',
                        'title' => '编辑角色',
                        'route' => 'admin.role.edit',
                        'icon' => '',
                        'type' => 2,
                        'sort' => 23,
                        'is_menu' => 0,
                    ],
                    [
                        'name' => 'system.role.destroy',
                        'title' => '删除角色',
                        'route' => 'admin.role.destroy',
                        'icon' => '',
                        'type' => 2,
                        'sort' => 24,
                        'is_menu' => 0,
                    ],
                    [
                        'name' => 'system.role.permission',
                        'title' => '分配权限',
                        'route' => 'admin.role.permission',
                        'icon' => '',
                        'type' => 2,
                        'sort' => 25,
                        'is_menu' => 0,
                    ],

                ],
            ],
            [
                'name' => 'system.user',
                'title' => '管理员管理',
                'route' => 'admin.admin.showPage',
                'icon' => 'layui-icon-template',
                'type' => 1,
                'sort' => 26,
                'is_menu' => 1,
                'children' => [
                    [
                        'name' => 'system.user.create',
                        'title' => '添加用户',
                        'route' => 'admin.admin.store',
                        'icon' => '',
                        'type' => 2,
                        'sort' => 27,
                        'is_menu' => 0,
                    ],
                    [
                        'name' => 'system.user.edit',
                        'title' => '编辑用户',
                        'route' => 'admin.admin.update',
                        'icon' => '',
                        'type' => 2,
                        'sort' => 28,
                        'is_menu' => 0,
                    ],
                    [
                        'name' => 'system.user.destroy',
                        'title' => '删除用户',
                        'route' => 'admin.admin.destroy',
                        'icon' => '',
                        'type' => 2,
                        'sort' => 29,
                        'is_menu' => 0,
                    ],
                ],
            ],
            [
                'name' => 'configuration.config',
                'title' => '系统配置',
                'route' => 'admin.config',
                'icon' => 'layui-icon-template',
                'type' => 1,
                'sort' => 44,
                'is_menu' => 1,
                'children' => [
                    [
                        'name' => 'configuration.config.store',
                        'title' => '添加配置',
                        'route' => 'admin.config.store',
                        'icon' => '',
                        'type' => 2,
                        'sort' => 45,
                        'is_menu' => 0,
                    ],
                    [
                        'name' => 'configuration.config.update',
                        'title' => '编辑配置',
                        'route' => 'admin.config.update',
                        'icon' => '',
                        'type' => 2,
                        'sort' => 46,
                        'is_menu' => 0,
                    ],
                ],
            ],

        ],
    ],
];
